[helm]Create keystone public service failed with nil external vip
When user try to install keystone-public-svc with default value.
Helm will installed failed with following messages

$ helm install microservice/keystone-public-svc
Created tunnel using local port: '41270'
SERVER: "localhost:41270"
CHART PATH: /home/lyan/helm/microservice/keystone-public-svc
Error: error validating "": error validating data: unexpected nil value
for field spec.externalIPs[0]

Keystone-public-svc will default enable external port, this will cause
svc yaml will need to get externa_vip value. But it will not been assign
any value. Therefore the svc yaml will output:

```
externalIPs:
    -
```

Maybe we should check whether external port had been enable and external vip had been added,
then assign external vip.

Change-Id: If74b97036d451420a2dbfef2786d9015657a47ac
Closed-Bug: 1670979